services:
  PixelFederation\CodingStandards\GrumPHP\Task\DoctrineSchemaValidateTask:
    class: PixelFederation\CodingStandards\GrumPHP\Task\DoctrineSchemaValidateTask
    arguments:
      - "@process_builder"
      - "@formatter.raw_process"
    tags:
      - { name: grumphp.task, task: doctrine_schema_validate }

  PixelFederation\CodingStandards\GrumPHP\Task\ComposerInstallCheckTask:
    class: PixelFederation\CodingStandards\GrumPHP\Task\ComposerInstallCheckTask
    arguments:
      - "@process_builder"
      - "@formatter.raw_process"
    tags:
      - { name: grumphp.task, task: composer_install_check }

  PixelFederation\CodingStandards\GrumPHP\Task\PhpMdExtendedTask:
    class: PixelFederation\CodingStandards\GrumPHP\Task\PhpMdExtendedTask
    arguments:
      - "@process_builder"
      - "@formatter.raw_process"
    tags:
      - { name: grumphp.task, task: phpmd_extended }
